package org.airyny.spring.learn.mybatis.pub.dao.dev;

import java.util.List;
import org.airyny.spring.learn.mybatis.pub.model.dev.SysAdmininfo;
import org.airyny.spring.learn.mybatis.pub.model.dev.SysAdmininfoExample;
import org.apache.ibatis.annotations.Param;

public interface SysAdmininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    long countByExample(SysAdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int deleteByExample(SysAdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int insert(SysAdmininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int insertSelective(SysAdmininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    List<SysAdmininfo> selectByExample(SysAdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    SysAdmininfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysAdmininfo record, @Param("example") SysAdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysAdmininfo record, @Param("example") SysAdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysAdmininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admininfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAdmininfo record);
}