package org.airyny.spring.learn.mybatis.pub.dao.dev;

import java.util.List;
import org.airyny.spring.learn.mybatis.pub.model.dev.SysUserinfo;
import org.airyny.spring.learn.mybatis.pub.model.dev.SysUserinfoExample;
import org.apache.ibatis.annotations.Param;

public interface SysUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    long countByExample(SysUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int insert(SysUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int insertSelective(SysUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    List<SysUserinfo> selectByExample(SysUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    SysUserinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysUserinfo record, @Param("example") SysUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysUserinfo record, @Param("example") SysUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserinfo record);
}